version: "3.9"
services:

  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
    networks:
      - yolo
  
  client:
    container_name: yolo_client
    restart: always
    build: client/
    ports:
      - 3000:3000
    networks:
      - yolo

  backend:
    container_name: yolo_backend
    restart: always
    build: backend/
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    networks:
      - yolo

volumes:
  mongo_db: {}
