version: "3.9"
services:

  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

  #node services
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: yolo_db
      NAME: yolo
    depends_on:
      - mongo_db

  client:
    container_name: yolomy_client
    restart: unless-stopped
    build: client/
    ports:
      - 3000:3000
    networks:
      - yolomy
  
  backend:
    container_name: yolomy_backend
    restart: unless-stopped
    build: backend/
    ports:
      - 5000:5000
    depends_on:
      - mongo_db
    networks:
      - yolomy

networks:
  yolomy:
    driver: bridge

volumes:
  mongo_db: {}
